### PR TITLE
#120: update: types for the wdio element

### PR DESCRIPTION
**Pull request by elaichenkov**
**Changes:**

* Fixed types for the wdio element 
* Created `element.types` file to have one entry point for changed types in future
* Updated documentation
* Included `tests` directory for ts check to prevent such issues in future
* Updated `packag.json` to set explicitly files that should be included in the npm package.

### CODE REVIEW

**Comment by christian-bromann** [comment]
Would this break tests for sync users? I wonder if we should just have it this way:
```ts
export type StringOrElement = string | WebdriverIO.Element | ChainablePromiseElement<Element<'async'>>;
```

What do you think?

**Comment by elaichenkov** [comment]
> Would this break tests for sync users? I wonder if we should just have it this way:
> 
> ```ts
> export type StringOrElement = string | WebdriverIO.Element | ChainablePromiseElement<Element<'async'>>;
> ```
> 
> What do you think?

I'm not sure that worked for sync mode before. Even more, I thought that sync mode is deprecated already.

**Review by christian-bromann — APPROVED** [review]
> Even more, I thought that sync mode is deprecated already.

It is, just wanted to make sure that we don't break peoples test. If you can confirm this wasn't working for sync before we can go ahead and merge then. Feel free to trigger a `patch` release if you like.

**Comment by elaichenkov** [comment]
> It is, just wanted to make sure that we don't break peoples test. If you can confirm this wasn't working for sync before we can go ahead and merge then. Feel free to trigger a patch release if you like.

It works for sync mode with these changes:
image

**Comment by christian-bromann** [comment]
Awesome, let's :shipit:

**Comment by elaichenkov** [comment]
@christian-bromann 
Hmmm. I just checked it with published changes and it doesn't work for sync mode. However, I checked it with the previous version and it doesn't work either. Anyway, I'll try to fix it tomorrow.

image

**Pull request merged**
